services:
  jekyll:
    image: jekyll/jekyll:4
    ports:
      - "4000:4000"
      - "35729:35729"
    volumes:
      - .:/srv/jekyll
    command: >
      bash -lc "
      gem install webrick >/dev/null &&
      bundle install || true &&
      jekyll serve --host 0.0.0.0 --livereload --force_polling --destination /tmp/_site
      "
